name: front end pipeline

on:
 push:
   branches:
   - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: check out 
      uses: actions/checkout@v4
    
    - name: set up node js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: install dependencies
      run: |
        npm install
        npm run build
    
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: dist
    
    
        
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: download artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
    
    - name: ssh to vm
      run: |
       sshpass -p "${{ secrets.PASSWORD }}" ssh -o StrictHostKeyChecking=no adminuser@${{ secrets.HOST }} << 'EOF'
       sudo apt update
       sudo apt install nginx -y
       EOF
       sshpass -p "${{secrets.PASSWORD}}" scp -o StrictHostKeyChecking=no -r $GITHUB_WORKSPACE/* adminuser@${{secrets.HOST}}:/var/www/html
    